#!/usr/bin/env python3
"""
gzip_to_header.py — Compress an HTML file and emit a C header containing a gzip byte array.

Usage:
    python tools/gzip_to_header.py <input.html> <output.h>

The variable name is derived from the input filename stem (UPPER_SNAKE_CASE).
Example:
    manual_control.html  ->  MANUAL_CONTROL_HTML_GZ / MANUAL_CONTROL_HTML_GZ_LEN
"""

import sys
import gzip
import re
from pathlib import Path


def to_varname(path: str) -> str:
    """Derive an UPPER_SNAKE_CASE prefix from a file path stem."""
    stem = Path(path).stem          # e.g. "manual_control"
    return re.sub(r'[^a-zA-Z0-9]', '_', stem).upper()  # e.g. "MANUAL_CONTROL"


def format_bytes(data: bytes, indent: str = "  ", cols: int = 16) -> str:
    """Format a bytes object as a comma-separated hex literal, 'cols' values per line."""
    chunks = [data[i:i + cols] for i in range(0, len(data), cols)]
    return (",\n" + indent).join(
        ", ".join(f"0x{b:02x}" for b in chunk) for chunk in chunks
    )


def main() -> None:
    if len(sys.argv) != 3:
        print(f"Usage: {Path(sys.argv[0]).name} <input.html> <output.h>", file=sys.stderr)
        sys.exit(1)

    in_path  = sys.argv[1]
    out_path = sys.argv[2]

    with open(in_path, "rb") as f:
        raw = f.read()

    compressed = gzip.compress(raw, compresslevel=9)

    var        = to_varname(in_path)
    array_name = f"{var}_HTML_GZ"
    len_name   = f"{var}_HTML_GZ_LEN"

    byte_lines = format_bytes(compressed)

    header = f"""\
// Auto-generated by tools/gzip_to_header.py — do not edit.
// Source:      {in_path}
// Regenerate: python tools/gzip_to_header.py {in_path} {out_path}
//
// Original size: {len(raw)} bytes
// Gzip level 9:  {len(compressed)} bytes ({100 * len(compressed) // len(raw)}% of original)
#pragma once

// Define USE_PROGMEM before including this file to store the data in flash memory.
// On ESP32, PROGMEM has no effect on placement but keeps the intent explicit.
#ifdef USE_PROGMEM
#include <pgmspace.h>
  const uint8_t {array_name}[] PROGMEM = 
#else
  const uint8_t {array_name}[]         = 
#endif
{{
  {byte_lines}
}};
const size_t {len_name} = sizeof({array_name});
"""

    with open(out_path, "w") as f:
        f.write(header)

    print(f"{in_path} -> {out_path}  ({len(raw)} B -> {len(compressed)} B gzip level 9)")


if __name__ == "__main__":
    main()
